Keep moving towards a final generated report.

diff --git a/3-host b/3-host
--- a/3-host
+++ b/3-host
@@ -299,28 +299,28 @@ REPORTHEADER
 	echo "=================================================[Main package faults]"
 	pushd ./res/sourced/ >/dev/null
 	VALIDARCHES=(any x86_64 i686 arm armv6h armv7h) # Order these with most popular first, since inarray ends early in such cases.
-	VALIDOPTIONS="strip\|docs\|libtool\|staticlibs\|emptydirs\|zipman\|purge\|upx\|debug\|ccache\|distcc\|buildflags\|makeflags"
-	VALIDILICENSES="AGPL\|AGPL3\|Artistic2.0\|CCPL\|CDDL\|CPL\|EPL\|FDL\|FDL1.2\|FDL1.3\|GPL\|GPL2\|GPL3\|LGPL\|LGPL2.1\|LGPL3\|LPPL\|MPL\|PerlArtistic\|PHP\|PSF\|RUBY\|W3C\|ZPL\|zsync\|BSD\|MIT\|Python\|zlib/libpng"
-	VALIDLICENSES="Apache\|APACHE"
+	VALIDOPTIONS=(strip docs libtool staticlibs emptydirs zipman purge upx debug ccache distcc buildflags makeflags)
+	VALIDILICENSES=(AGPL AGPL3 Artistic2.0 CCPL CDDL CPL EPL FDL FDL1.2 FDL1.3 GPL GPL2 GPL3 LGPL LGPL2.1 LGPL3 LPPL MPL PerlArtistic PHP PSF RUBY W3C ZPL zsync BSD MIT Python zlib/libpng)
+	VALIDLICENSES=(Apache APACHE)
 	# End of array markers below for iteration assistance.
-	ALLPKGFIELDS=(pkgname pkgver pkgrel pkgdesc url '-') # REQUIRED STRINGS
+	ALLPKGFIELDS=(pkgname pkgver pkgrel pkgdesc url '-') # REQUIRED STRINGS (pkgname is a special case in the event of split packages)
 	ALLPKGFIELDS+=(arch license '--') # REQUIRED ARRAYS
 	ALLPKGFIELDS+=(pkgdir srcdir startdir epoch pkgbase groups install changelog '---') # OTHER STRINGS
 	ALLPKGFIELDS+=(depends optdepends makedepends checkdepends provides conflicts replaces backup options source noextract md5sums sha1sums sha256sums sha384sums sha512sums) # OTHER ARRAYS
 	[[ "$VERBOSITY" -ge 3 ]] && BASEANDDEVEL=$(expac -Sg '%n' base base-devel | SHELL=/usr/bin/bash parallel -j8 'pactree -sl {}' | awk '{print $1;}' | awk 'BEGIN{RS=ORS="\n"}!a[$0]++' | SHELL=/usr/bin/bash parallel -j8 'echo {}; expac -S1 "%S" {} | sed "s/  /\n/g" | grep -v "\.so$"' | awk 'BEGIN{RS=ORS="\n"}!a[$0]++')
 	find . -type f | sort | SHELL=/usr/bin/bash parallel -k -N 25 -j8 '
-		inarray() { local n=$1 h; shift; for h; do [[ $n = "$h" ]] && return; done; return 1; }
-		validate_pkgname() { [[ "$ROVERBOSITY" -ge 4 ]] && [[ "$pkgname" != "$ROEXTRACTEDDIRNAME" ]] && echo "[*] Unzipped directory name and pkgname do not match.  ($ROEXTRACTEDDIRNAME =/= $pkgname)"; }
+		inarray() { local insensitive=$1 n=$2 h; shift 2; $insensitive && shopt -s nocasematch; for h; do [[ $n = "$h" ]] || continue; $insensitive && shopt -u nocasematch; return 0; done; shopt -u nocasematch; return 1; }
+		validate_pkgname() { [[ "$ROVERBOSITY" -ge 4 ]] && [[ "$pkgname" != "$ROEXTRACTEDDIRNAME" ]] && [[ "$pkgbase" != "$ROEXTRACTEDDIRNAME" ]] && echo "[*] Unzipped directory name and pkgname do not match.  ($ROEXTRACTEDDIRNAME =/= $pkgname)"; }
 		validate_pkgver() { [[ "$pkgrel" =~ [^A-Za-z0-9._] ]] && echo "[*] Disallowed pkgver format.  ($pkgver)"; }
 		validate_pkgrel() { [[ "$ROVERBOSITY" -ge 3 ]] && [[ "$pkgrel" =~ [^0-9] ]] && echo "[*] Non-integer or negative pkgrel.  ($pkgrel)"; }
-		validate_pkgdesc() { [[ "$ROVERBOSITY" -ge 3 ]] && grep -qwf <(echo "$pkgname") <(echo "$pkgdesc") && echo "[*] Found pkgname inside pkgdesc."; }
-		validate_url() { grep -qFf <(echo "$url" | sed "\|://|!d;s|/$||") "../urllist" && echo "[*] Could not connect to address in url field.  ($url)"; }
-		validate_arch() { [[ "$ROVERBOSITY" -ge 2 ]] && for ARCHITECTURENAME in "${arch[@]}"; do inarray "$ARCHITECTURENAME" "${ROVALIDARCHES[@]}" || echo "[*] Architecture not recognised.  ($ARCHITECTURENAME)"; done; }
-		validate_license() { return; }
+		validate_pkgdesc() { [[ "$ROVERBOSITY" -ge 3 ]] && local COMPAREWITH=$(if [[ "$pkgbase" != "" ]]; then echo "$pkgbase"; else echo "$pkgname"; fi); grep -qwf <(echo "$pkgname") <(echo "$COMPAREWITH") && echo "[*] Found package name inside pkgdesc. ($COMPAREWITH)"; { { [[ "$ROVERBOSITY" == 3 ]] && [[ ${#pkgdesc} -gt 150 ]]; } || { [[ "$ROVERBOSITY" == 4 ]] && [[ ${#pkgdesc} -gt 100 ]]; } || { [[ "$ROVERBOSITY" -ge 5 ]] && [[ ${#pkgdesc} -gt 70 ]]; } } && echo "[*] Pkgdesc is excessively long. (${#pkgdesc} chars)"; }
+		validate_url() { grep -qxFf <(echo "$url" | sed "\|://|!d;s|/$||") "../urllist" && echo "[*] Could not connect to address in url field.  ($url)"; }
+		validate_arch() { [[ "$ROVERBOSITY" -ge 2 ]] && local ARCHITECTURENAME && for ARCHITECTURENAME in "${arch[@]}"; do inarray false "$ARCHITECTURENAME" "${ROVALIDARCHES[@]}" || echo "[*] Architecture not recognised.  ($ARCHITECTURENAME)"; done; }
+		validate_license() { [[ "$ROVERBOSITY" -ge 4 ]] && local LICENSENAME && for LICENSENAME in "${license[@]}"; do [[ "$LICENSENAME" == "custom" ]] || { [[ "$LICENSENAME" == "custom:"?* ]] && { ! inarray true "${LICENSENAME#custom:}" "${ROVALIDILICENSES[@]}" && ! inarray false "${LICENSENAME#custom:}" "${ROVALIDLICENSES[@]}"; }; } || inarray true "$LICENSENAME" "${ROVALIDILICENSES[@]}" || inarray false "$LICENSENAME" "${ROVALIDLICENSES[@]}" || echo "[*] Bad license name.  ($LICENSENAME)"; done; }
 		validate_pkgdir() { [[ "$pkgdir" != "" ]] && echo "[*] Sets pkgdir.  (To $pkgdir)"; }
 		validate_srcdir() { [[ "$srcdir" != "" ]] && echo "[*] Sets srcdir.  (To $srcdir)"; }
 		validate_startdir() { [[ "$startdir" != "" ]] && echo "[*] Sets startdir.  (To $startdir)"; }
-		validate_epoch() { return; }
+		validate_epoch() { [[ "$ROVERBOSITY" -ge 3 ]] && [[ "$epoch" =~ [^0-9] ]] && echo "[*] Non-integer or negative epoch.  ($epoch)"; }
 		validate_pkgbase() { return; }
 		validate_groups() { return; }
 		validate_install() { [[ $install != "" ]] && [ ! -f "../../prep/ext/$ROEXTRACTEDDIRNAME/$install" ] && echo "[*] Install file not found in archive.  ($install)"; }
@@ -333,30 +333,45 @@ REPORTHEADER
 		validate_conflicts() { return; }
 		validate_replaces() { return; }
 		validate_backup() { return; }
-		validate_options() { return; }
-		validate_source() { return; }
+		validate_options() { [[ "$ROVERBOSITY" -ge 3 ]] && local OPTIONNAME && for OPTIONNAME in "${options[@]}"; do { [[ $OPTIONNAME == "" ]] || inarray false "${OPTIONNAME#!}" "${ROVALIDOPTIONS[@]}"; } || echo "[*] Unknown option.  ($OPTIONNAME)"; done; }
+		validate_source() { local COMPARETO=$(IFS=$'"'\n'"'; grep -Fxf <(echo "${source[*]}" | sed "\|://|!d;s/::/\n/;s/^.*\n//;s|/$||") "../urllist"); [[ "$COMPARETO" != "" ]] && echo "[*] Could not connect to the following sources:" && echo "$COMPARETO"; }
 		validate_noextract() { return; }
-		validate_md5sums() { return; }
-		validate_sha1sums() { return; }
-		validate_sha256sums() { return; }
-		validate_sha384sums() { return; }
-		validate_sha512sums() { return; }
+		validate_md5sums() { [[ "${#md5sums[@]}" != 0 ]] && NUMSUMTYPES=$((NUMSUMTYPES + 1)) && local MD5SUM && for MD5SUM in "${md5sums[@]}"; do { [[ "$MD5SUM" == "SKIP" ]] || [[ "$MD5SUM" =~ ^[0-9a-f]{32}$ ]]; } && NUMSUMS=$((NUMSUMS + 1)) || echo "Malformed md5sum.  ($MD5SUM)"; done; }
+		validate_sha1sums() { [[ "${#sha1sums[@]}" != 0 ]] && NUMSUMTYPES=$((NUMSUMTYPES + 1)) && local SHA1SUM && for SHA1SUM in "${sha1sums[@]}"; do { [[ "$SHA1SUM" == "SKIP" ]] || [[ "$SHA1SUM" =~ ^[0-9a-f]{40}$ ]]; } && NUMSUMS=$((NUMSUMS + 1)) || echo "Malformed sha1sum.  ($SHA1SUM)"; done; }
+		validate_sha256sums() { [[ "${#sha256sums[@]}" != 0 ]] && NUMSUMTYPES=$((NUMSUMTYPES + 1)) local SHA256SUM && for SHA256SUM in "${sha256sums[@]}"; do { [[ "$SHA256SUM" == "SKIP" ]] || [[ "$SHA256SUM" =~ ^[0-9a-f]{64}$ ]]; } && NUMSUMS=$((NUMSUMS + 1)) || echo "Malformed sha256sum.  ($SHA256SUM)"; done; }
+		validate_sha384sums() { [[ "${#sha384sums[@]}" != 0 ]] && NUMSUMTYPES=$((NUMSUMTYPES + 1)) local SHA384SUM && for SHA384SUM in "${sha384sums[@]}"; do { [[ "$SHA384SUM" == "SKIP" ]] || [[ "$SHA384SUM" =~ ^[0-9a-f]{96}$ ]]; } && NUMSUMS=$((NUMSUMS + 1)) || echo "Malformed sha384sum.  ($SHA384SUM)"; done; }
+		validate_sha512sums() { [[ "${#sha512sums[@]}" != 0 ]] && NUMSUMTYPES=$((NUMSUMTYPES + 1)) local SHA512SUM && for SHA512SUM in "${sha512sums[@]}"; do { [[ "$SHA512SUM" == "SKIP" ]] || [[ "$SHA512SUM" =~ ^[0-9a-f]{128}$ ]]; } && NUMSUMS=$((NUMSUMS + 1)) || echo "Malformed sha512sum.  ($SHA512SUM)"; done; }
+		validate_archivefiles() { return; }
 
 		INPUT=( {} )
 		for PACKAGE in "${INPUT[@]}"
 		do
 			EXTRACTEDDIRNAME="${PACKAGE##*/}"
+			APPLICABLEARCHES="${EXTRACTEDDIRNAME##*-}"
 			EXTRACTEDDIRNAME="${EXTRACTEDDIRNAME%-*}"
 			RESULT=$(
 				readonly ROEXTRACTEDDIRNAME="$EXTRACTEDDIRNAME"
 				readonly ROVERBOSITY="'"$VERBOSITY"'"
 				readonly ROALLPKGFIELDS=('"${ALLPKGFIELDS[@]}"')
+				readonly ROVALIDOPTIONS=('"${VALIDOPTIONS[@]}"')
 				readonly ROVALIDARCHES=('"${VALIDARCHES[@]}"')
+				readonly ROVALIDILICENSES=('"${VALIDILICENSES[@]}"')
+				readonly ROVALIDLICENSES=('"${VALIDLICENSES[@]}"')
 				source "$PACKAGE" 2>/dev/null
 				[[ $(expr index "$(declare -p)" $'"'\r'"') != 0 ]] && echo "Aborting: Found line feeds.  Remember, CRLF PKGBUILDs cannot be sourced by makepkg." && exit
 				
+				if [[ "$ROVERBOSITY" -ge 3 ]]; then
+					ALLSETVARS=($(sed "/^_/d;s/=.*//" "$PACKAGE"))
+					for SETVARIABLE in "${ALLSETVARS[@]}"
+					do
+						{ inarray false "$SETVARIABLE" "${ROALLPKGFIELDS[@]}" && ! [[ "$SETVARIABLE" =~ "-+" ]]; } || echo "[*] Unknown non-underscored variable $SETVARIABLE set."
+					done
+				fi
+
 				REQUIREDFIELD=true
 				ISSTRING=true
+				NUMSUMS=0
+				NUMSUMTYPES=0
 				for PKGBUILDFIELD in "${ROALLPKGFIELDS[@]}"
 				do
 					$REQUIREDFIELD && [[ "$PKGBUILDFIELD" == "-" ]] && ISSTRING=false && continue
@@ -365,15 +380,19 @@ REPORTHEADER
 
 					$REQUIREDFIELD && $ISSTRING && [[ "${!PKGBUILDFIELD}" == "" ]] && echo "[*] $PKGBUILDFIELD is not set."
 					$REQUIREDFIELD && ! $ISSTRING && TMPVAR="$PKGBUILDFIELD""[@]" && [[ "${!TMPVAR}" == "" ]] && echo "[*] $PKGBUILDFIELD is not set."
-					
+
 					validate_$PKGBUILDFIELD
 				done
+
+				{ [[ "$NUMSUMS" != "${#source[@]}" ]] || [[ "$NUMSUMTYPES" -gt 1 ]]; } && echo "[*] Contains confusing source checksums.  ($NUMSUMS checksums in $NUMSUMTYPES hash formats, ${#source[@]} sources.)"
+
+				validate_archivefiles
 
 				exit 0
 			)
 			[[ $? == 1 ]] && RESULT="Aborting: Could not load data, likely due to use of an associative array."
 			
-			[[ $RESULT != "" ]] && echo "$EXTRACTEDDIRNAME" && echo "$RESULT" && echo
+			[[ $RESULT != "" ]] && echo "$EXTRACTEDDIRNAME ($APPLICABLEARCHES)" && echo "$RESULT" && echo
 		done
 	'
 	popd >/dev/null
